// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARFWSH3EVcBy8piIW7AKnCTk61YTrEwws',
    appId: '1:460671955266:web:2dd07ead9bce2adc9298db',
    messagingSenderId: '460671955266',
    projectId: 'aplicativo-flutter-pdm',
    authDomain: 'aplicativo-flutter-pdm.firebaseapp.com',
    storageBucket: 'aplicativo-flutter-pdm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSvFRIL09-MSmzHOK2WdSahXqP8v0EZVs',
    appId: '1:460671955266:android:af5be0c35171c4809298db',
    messagingSenderId: '460671955266',
    projectId: 'aplicativo-flutter-pdm',
    storageBucket: 'aplicativo-flutter-pdm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBueWeP3DXfu-1lZVAXZhnIMQ0J5vKBM4g',
    appId: '1:460671955266:ios:13146d5b5d2af95c9298db',
    messagingSenderId: '460671955266',
    projectId: 'aplicativo-flutter-pdm',
    storageBucket: 'aplicativo-flutter-pdm.firebasestorage.app',
    iosBundleId: 'com.example.aplicativoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBueWeP3DXfu-1lZVAXZhnIMQ0J5vKBM4g',
    appId: '1:460671955266:ios:13146d5b5d2af95c9298db',
    messagingSenderId: '460671955266',
    projectId: 'aplicativo-flutter-pdm',
    storageBucket: 'aplicativo-flutter-pdm.firebasestorage.app',
    iosBundleId: 'com.example.aplicativoFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARFWSH3EVcBy8piIW7AKnCTk61YTrEwws',
    appId: '1:460671955266:web:0dea8c6197bb0a099298db',
    messagingSenderId: '460671955266',
    projectId: 'aplicativo-flutter-pdm',
    authDomain: 'aplicativo-flutter-pdm.firebaseapp.com',
    storageBucket: 'aplicativo-flutter-pdm.firebasestorage.app',
  );
}
